### ISSUE TITLE
 Improve repository structure

### ISSUE THREAD

**Issue by hugueskamba** [FreeRTOS/iot-reference-arm-corstone3xx#25]
**Is your feature request related to a problem? Please describe.**

In the fast-paced world of software development, maintaining a well-organised and structured code repository is crucial.
This document outlines changes made aimed at enhancing the clarity, consistency, and overall efficiency of our code base.
By adopting standardised naming conventions, reorganising files, and redefining subdirectory structures, we aim to streamline collaboration, simplify maintenance, and make the code base more approachable for both current and future developers. Additionally, the incorporation of clear CMake targets will improve the build process, promoting a more robust and scalable development environment.
These changes are essential for fostering a sustainable and agile development workflow, ultimately leading to increased productivity and a higher quality code base.

**Describe the solution you'd like**
Please read the description of the changes in [this](https://github.com/hugueskamba/iot-reference-arm-corstone3xx/blob/feature/restructure-project/docs/project_organisation.md) document.

**Comment by bradleysmith23** [comment]
Closing as related PR is merged. Thank you!
